[theme]
primaryColor = "#3b82f6"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e293b"
textColor = "#ffffff"
font = "sans serif"

[server]
maxUploadSize = 200
maxMessageSize = 200
headless = true
enableCORS = false
